# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: Z2hwXzhzM2dRckpyb2l6dlBOZ1BoUXV1N0NiSFdDZGpKcTNVc3JNdw==
